name: New Release
on:
  workflow_dispatch:

jobs:
 release:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Init values
       id: values
       run: |
          version=$(grep -Po -m 1 '(?<=versionName ).*' ./app/build.gradle | tr -d \")
          echo ::set-output name=name::hKtweaks v$version
          echo ::set-output name=tag::v$(echo $version | tr -d "\- OneUI")
          echo ::set-output name=apk::hKtweaks_v$(echo $version | sed -r 's/[- ]+/_/g')
     - name: Create release
       id: create_release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         release_name: ${{ steps.values.outputs.name }}
         tag_name: ${{ steps.values.outputs.tag }}
         body: changelog
     - name: Add OneUI 3 apk
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }} 
         asset_path: ./app/release-oneui3/release/hKtweaks.apk
         asset_name: ${{ steps.values.outputs.apk }}_3.apk
         asset_content_type: application/vnd.android.package-archive
     - name: Add OneUI 4 apk
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }} 
         asset_path: ./app/release-oneui4/release/hKtweaks.apk
         asset_name: ${{ steps.values.outputs.apk }}_4.apk
         asset_content_type: application/vnd.android.package-archive
